// Generated by CoffeeScript 1.7.1
var Mustache, fs, loadPartials, path, render;

Mustache = require('mustache');

fs = require('fs');

path = require('path');

loadPartials = function(dir) {
  var conts, file, partialName, retval, _i, _len;
  conts = fs.readdirSync(dir);
  retval = {};
  for (_i = 0, _len = conts.length; _i < _len; _i++) {
    file = conts[_i];
    if (!/\.mustache$/.test(file)) {
      continue;
    }
    partialName = file.replace(/\.mustache$/, '');
    retval[partialName] = function() {
      return fs.readFileSync(path.join(dir, "" + partialName + ".mustache")).toString();
    };
  }
  return retval;
};

module.exports = render = function(viewFile, args, callback) {
  return fs.readFile(viewFile, function(e, cont) {
    console.log(loadPartials(args.settings.partials));
    return callback(e, Mustache.render(cont.toString(), args, loadPartials(args.settings.partials)));
  });
};
